# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - R -e 'tensorflow::install_tensorflow()'
  - curl -OL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - mv protoc3/bin/* /usr/local/bin/
  - mv protoc3/include/* /usr/local/include/
  - chmod a+x /usr/local/bin/protoc
  - rm -f protoc-3.5.1-linux-x86_64.zip
