# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true

addons:
  apt:
    packages:
    - libprotobuf-dev

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - R -e 'tensorflow::install_tensorflow()'
