# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true

addons:
  apt:
    packages:
    - autoconf 
    - automake 
    - libtool
    - curl
    - make 
    - g++ 
    - unzip
  

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv protobuf ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo easy_install pip ;fi
  - R -e 'tensorflow::install_tensorflow()'
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash tools/install-protobuf.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install protobuf    ; fi

os:
  - linux
  - osx
