// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// raw_to_char_
std::string raw_to_char_(const RawVector& x);
RcppExport SEXP _tfrecords_raw_to_char_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RawVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(raw_to_char_(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tfrecords_raw_to_char_", (DL_FUNC) &_tfrecords_raw_to_char_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tfrecords(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
