# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

raw_to_char_ <- function(x) {
    .Call('_tfrecords_raw_to_char_', PACKAGE = 'tfrecords', x)
}

