# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_tfrecord <- function(x, path) {
    .Call('_tfrecords_write_tfrecord', PACKAGE = 'tfrecords', x, path)
}

write_tfrecords_ <- function(data, description, n, path) {
    .Call('_tfrecords_write_tfrecords_', PACKAGE = 'tfrecords', data, description, n, path)
}

tfrecord_shutdown <- function() {
    .Call('_tfrecords_tfrecord_shutdown', PACKAGE = 'tfrecords')
}

write_test_example <- function(path) {
    .Call('_tfrecords_write_test_example', PACKAGE = 'tfrecords', path)
}

