# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DummyExample <- function() {
    .Call('_tfrecords_DummyExample', PACKAGE = 'tfrecords')
}

tfrecord_shutdown <- function() {
    .Call('_tfrecords_tfrecord_shutdown', PACKAGE = 'tfrecords')
}

